# Generated by Django 3.1 on 2020-09-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('times_eaten', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('cook_time', models.PositiveIntegerField()),
                ('portion_number', models.PositiveIntegerField()),
                ('original_recipe_link', models.URLField()),
                ('other_link', models.URLField(blank=True)),
                ('original_recipe_creator', models.CharField(max_length=40)),
                ('original_recipe_name', models.CharField(max_length=60)),
                ('recipe_category', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groceries_app.ingredient')),
                ('meal_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groceries_app.meal')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groceries_app.measurement')),
            ],
        ),
    ]
