# Generated by Django 3.1 on 2020-09-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='original_recipe_creator',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='original_recipe_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='other_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='portion_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe_link_one',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe_link_two',
            field=models.URLField(blank=True, null=True),
        ),
    ]
