# Generated by Django 3.1 on 2020-09-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0004_auto_20200922_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='specialty',
        ),
    ]
