# Generated by Django 3.1 on 2020-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0005_remove_ingredient_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
