# Generated by Django 3.1 on 2020-10-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0006_ingredientquantity_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='optional',
            new_name='optional_ingredient',
        ),
    ]
