# Generated by Django 3.1 on 2020-10-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0007_auto_20201005_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='cook_time',
            new_name='cook_time_in_minutes',
        ),
    ]
