# Generated by Django 3.1.2 on 2020-10-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0008_auto_20201006_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='optional',
        ),
    ]
