# Generated by Django 3.1.2 on 2020-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0008_auto_20201006_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='optional',
        ),
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images'),
        ),
    ]
