# Generated by Django 3.1.2 on 2020-12-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='specialty_location',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='groceries_app.category'),
        ),
    ]
