# Generated by Django 3.1.2 on 2020-12-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0013_auto_20201203_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredient']},
        ),
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'verbose_name_plural': 'Ingredient Quantities'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['measurement']},
        ),
    ]
